### ISSUE TITLE
Add Usage Examples

### ISSUE THREAD

**Issue by SaltedBlowfish** [alexcastillo/redux-airbrake#2]
As a developer using this package, I expect to find the following usage examples in the README:

- Using filters to allow certain conditions to prevent sending airbrake errors
- Sending a test error

**Comment by alexcastillo** [comment]
Hey @SaltedBlowfish,

I've released a new version with some improvements, including examples of how to use filter.
For sending a test error, I didn't find a way provided by `airbrake-js`. Maybe open an issue there?

Thanks!

Alex
