### ISSUE TITLE
airbrake-js dependency update

### ISSUE THREAD

**Issue by liitfr** [alexcastillo/redux-airbrake#4]
Hello !
Thanks for sharing this helpful work.

`airbrake-js` latest version is now `1.1.0` but `redux-airbrake` requires a peer of `airbrake-js@0.*`
Would it be possible to update dependencies ?

Thanks again,
Mat

**Comment by alexcastillo** [comment]
Hey, Mat,

Thanks for reaching out. Any chance you can send a PR? I'll gladly merge it.

Best,

Alex
